import { Institution } from './types';

export const INDIAN_UNIVERSITIES: Institution[] = [
  // ==========================================
  // 1. ALL CENTRAL UNIVERSITIES OF INDIA
  // ==========================================
  {
    id: 'inst-in-cusb',
    name: 'Central University of South Bihar',
    country: 'India',
    city: 'Gaya',
    state: 'Bihar',
    abbreviations: ['CUSB', 'CU South Bihar'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-curaj',
    name: 'Central University of Rajasthan',
    country: 'India',
    city: 'Ajmer',
    state: 'Rajasthan',
    abbreviations: ['CURAJ', 'CU Rajasthan'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cuk',
    name: 'Central University of Kerala',
    country: 'India',
    city: 'Kasaragod',
    state: 'Kerala',
    abbreviations: ['CUK', 'CU Kerala'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cuj',
    name: 'Central University of Jharkhand',
    country: 'India',
    city: 'Ranchi',
    state: 'Jharkhand',
    abbreviations: ['CUJ', 'CU Jharkhand'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cuh',
    name: 'Central University of Haryana',
    country: 'India',
    city: 'Mahendragarh',
    state: 'Haryana',
    abbreviations: ['CUH', 'CU Haryana'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cupb',
    name: 'Central University of Punjab',
    country: 'India',
    city: 'Bathinda',
    state: 'Punjab',
    abbreviations: ['CUPB', 'CU Punjab'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cug',
    name: 'Central University of Gujarat',
    country: 'India',
    city: 'Gandhinagar',
    state: 'Gujarat',
    abbreviations: ['CUG', 'CU Gujarat'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cuhp',
    name: 'Central University of Himachal Pradesh',
    country: 'India',
    city: 'Dharamshala',
    state: 'Himachal Pradesh',
    abbreviations: ['CUHP', 'CU Himachal'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cujammu',
    name: 'Central University of Jammu',
    country: 'India',
    city: 'Jammu',
    state: 'Jammu and Kashmir',
    abbreviations: ['CU Jammu'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cukashmir',
    name: 'Central University of Kashmir',
    country: 'India',
    city: 'Ganderbal',
    state: 'Jammu and Kashmir',
    abbreviations: ['CU Kashmir'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cukarnataka',
    name: 'Central University of Karnataka',
    country: 'India',
    city: 'Kalaburagi',
    state: 'Karnataka',
    abbreviations: ['CUKar', 'CU Karnataka'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cuo',
    name: 'Central University of Odisha',
    country: 'India',
    city: 'Koraput',
    state: 'Odisha',
    abbreviations: ['CUO', 'CU Odisha'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cutn',
    name: 'Central University of Tamil Nadu',
    country: 'India',
    city: 'Thiruvarur',
    state: 'Tamil Nadu',
    abbreviations: ['CUTN', 'CU Tamil Nadu'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cuap',
    name: 'Central University of Andhra Pradesh',
    country: 'India',
    city: 'Anantapur',
    state: 'Andhra Pradesh',
    abbreviations: ['CUAP', 'CU Andhra'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-du',
    name: 'University of Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['DU', 'Delhi University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-jnu',
    name: 'Jawaharlal Nehru University',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['JNU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-jmi',
    name: 'Jamia Millia Islamia',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['JMI', 'Jamia'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-bhu',
    name: 'Banaras Hindu University',
    country: 'India',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    abbreviations: ['BHU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-amu',
    name: 'Aligarh Muslim University',
    country: 'India',
    city: 'Aligarh',
    state: 'Uttar Pradesh',
    abbreviations: ['AMU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-au-allahabad',
    name: 'University of Allahabad',
    country: 'India',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    abbreviations: ['UoA', 'Allahabad University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-bbau',
    name: 'Babasaheb Bhimrao Ambedkar University',
    country: 'India',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    abbreviations: ['BBAU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-visva-bharati',
    name: 'Visva-Bharati University',
    country: 'India',
    city: 'Santiniketan',
    state: 'West Bengal',
    abbreviations: ['Visva Bharati'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-uoh',
    name: 'University of Hyderabad',
    country: 'India',
    city: 'Hyderabad',
    state: 'Telangana',
    abbreviations: ['UoH', 'HCU', 'Hyderabad Central University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-eflu',
    name: 'English and Foreign Languages University',
    country: 'India',
    city: 'Hyderabad',
    state: 'Telangana',
    abbreviations: ['EFLU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-manuu',
    name: 'Maulana Azad National Urdu University',
    country: 'India',
    city: 'Hyderabad',
    state: 'Telangana',
    abbreviations: ['MANUU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-pondi',
    name: 'Pondicherry University',
    country: 'India',
    city: 'Puducherry',
    state: 'Puducherry',
    abbreviations: ['PU Pondicherry'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nehu',
    name: 'North-Eastern Hill University',
    country: 'India',
    city: 'Shillong',
    state: 'Meghalaya',
    abbreviations: ['NEHU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-tezpur',
    name: 'Tezpur University',
    country: 'India',
    city: 'Tezpur',
    state: 'Assam',
    abbreviations: ['TU Assam'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-assam-univ',
    name: 'Assam University',
    country: 'India',
    city: 'Silchar',
    state: 'Assam',
    abbreviations: ['AUS'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-mizoram',
    name: 'Mizoram University',
    country: 'India',
    city: 'Aizawl',
    state: 'Mizoram',
    abbreviations: ['MZU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nagaland',
    name: 'Nagaland University',
    country: 'India',
    city: 'Lumami',
    state: 'Nagaland',
    abbreviations: ['NU Nagaland'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-manipur',
    name: 'Manipur University',
    country: 'India',
    city: 'Imphal',
    state: 'Manipur',
    abbreviations: ['MU Manipur'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-rgu',
    name: 'Rajiv Gandhi University',
    country: 'India',
    city: 'Itanagar',
    state: 'Arunachal Pradesh',
    abbreviations: ['RGU Arunachal'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-sikkim',
    name: 'Sikkim University',
    country: 'India',
    city: 'Gangtok',
    state: 'Sikkim',
    abbreviations: ['SU Sikkim'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-tripura',
    name: 'Tripura University',
    country: 'India',
    city: 'Agartala',
    state: 'Tripura',
    abbreviations: ['TU Tripura'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-hnbgu',
    name: 'Hemvati Nandan Bahuguna Garhwal University',
    country: 'India',
    city: 'Srinagar',
    state: 'Uttarakhand',
    abbreviations: ['HNBGU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-ggu',
    name: 'Guru Ghasidas Vishwavidyalaya',
    country: 'India',
    city: 'Bilaspur',
    state: 'Chhattisgarh',
    abbreviations: ['GGU Bilaspur'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-dhsgsu',
    name: 'Doctor Harisingh Gour Vishwavidyalaya',
    country: 'India',
    city: 'Sagar',
    state: 'Madhya Pradesh',
    abbreviations: ['DHSGSU', 'Sagar University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-igntu',
    name: 'Indira Gandhi National Tribal University',
    country: 'India',
    city: 'Amarkantak',
    state: 'Madhya Pradesh',
    abbreviations: ['IGNTU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-mgcu',
    name: 'Mahatma Gandhi Central University',
    country: 'India',
    city: 'Motihari',
    state: 'Bihar',
    abbreviations: ['MGCU Motihari'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nalanda',
    name: 'Nalanda University',
    country: 'India',
    city: 'Rajgir',
    state: 'Bihar',
    abbreviations: ['NU Rajgir'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 2. ALL 23 INDIAN INSTITUTES OF TECHNOLOGY (IITs)
  // ==========================================
  {
    id: 'inst-in-iitb',
    name: 'Indian Institute of Technology Bombay',
    country: 'India',
    city: 'Mumbai',
    state: 'Maharashtra',
    abbreviations: ['IITB', 'IIT Bombay'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitd',
    name: 'Indian Institute of Technology Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['IITD', 'IIT Delhi'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitm',
    name: 'Indian Institute of Technology Madras',
    country: 'India',
    city: 'Chennai',
    state: 'Tamil Nadu',
    abbreviations: ['IITM', 'IIT Madras'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitk',
    name: 'Indian Institute of Technology Kanpur',
    country: 'India',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    abbreviations: ['IITK', 'IIT Kanpur'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitkgp',
    name: 'Indian Institute of Technology Kharagpur',
    country: 'India',
    city: 'Kharagpur',
    state: 'West Bengal',
    abbreviations: ['IIT KGP', 'IIT Kharagpur'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitr',
    name: 'Indian Institute of Technology Roorkee',
    country: 'India',
    city: 'Roorkee',
    state: 'Uttarakhand',
    abbreviations: ['IITR', 'IIT Roorkee'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitg',
    name: 'Indian Institute of Technology Guwahati',
    country: 'India',
    city: 'Guwahati',
    state: 'Assam',
    abbreviations: ['IITG', 'IIT Guwahati'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iith',
    name: 'Indian Institute of Technology Hyderabad',
    country: 'India',
    city: 'Sangareddy',
    state: 'Telangana',
    abbreviations: ['IITH', 'IIT Hyderabad'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iit-bhu',
    name: 'Indian Institute of Technology (BHU) Varanasi',
    country: 'India',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    abbreviations: ['IIT BHU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiti',
    name: 'Indian Institute of Technology Indore',
    country: 'India',
    city: 'Indore',
    state: 'Madhya Pradesh',
    abbreviations: ['IITI', 'IIT Indore'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitgn',
    name: 'Indian Institute of Technology Gandhinagar',
    country: 'India',
    city: 'Gandhinagar',
    state: 'Gujarat',
    abbreviations: ['IITGN', 'IIT Gandhinagar'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitrpr',
    name: 'Indian Institute of Technology Ropar',
    country: 'India',
    city: 'Rupnagar',
    state: 'Punjab',
    abbreviations: ['IIT Ropar', 'IITRPR'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitp',
    name: 'Indian Institute of Technology Patna',
    country: 'India',
    city: 'Patna',
    state: 'Bihar',
    abbreviations: ['IITP', 'IIT Patna'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitbbs',
    name: 'Indian Institute of Technology Bhubaneswar',
    country: 'India',
    city: 'Bhubaneswar',
    state: 'Odisha',
    abbreviations: ['IIT BBS', 'IIT Bhubaneswar'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitj',
    name: 'Indian Institute of Technology Jodhpur',
    country: 'India',
    city: 'Jodhpur',
    state: 'Rajasthan',
    abbreviations: ['IITJ', 'IIT Jodhpur'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitmandi',
    name: 'Indian Institute of Technology Mandi',
    country: 'India',
    city: 'Mandi',
    state: 'Himachal Pradesh',
    abbreviations: ['IIT Mandi'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitpkd',
    name: 'Indian Institute of Technology Palakkad',
    country: 'India',
    city: 'Palakkad',
    state: 'Kerala',
    abbreviations: ['IIT Palakkad', 'IIT PKD'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iittp',
    name: 'Indian Institute of Technology Tirupati',
    country: 'India',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    abbreviations: ['IIT Tirupati'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitism',
    name: 'Indian Institute of Technology (ISM) Dhanbad',
    country: 'India',
    city: 'Dhanbad',
    state: 'Jharkhand',
    abbreviations: ['IIT ISM', 'ISM Dhanbad'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitbhilai',
    name: 'Indian Institute of Technology Bhilai',
    country: 'India',
    city: 'Bhilai',
    state: 'Chhattisgarh',
    abbreviations: ['IIT Bhilai'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitgoa',
    name: 'Indian Institute of Technology Goa',
    country: 'India',
    city: 'Ponda',
    state: 'Goa',
    abbreviations: ['IIT Goa'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitjammu',
    name: 'Indian Institute of Technology Jammu',
    country: 'India',
    city: 'Jammu',
    state: 'Jammu and Kashmir',
    abbreviations: ['IIT Jammu'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iitdh',
    name: 'Indian Institute of Technology Dharwad',
    country: 'India',
    city: 'Dharwad',
    state: 'Karnataka',
    abbreviations: ['IIT Dharwad'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 3. ALL NATIONAL INSTITUTES OF TECHNOLOGY (NITs)
  // ==========================================
  {
    id: 'inst-in-nitt',
    name: 'National Institute of Technology Tiruchirappalli',
    country: 'India',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    abbreviations: ['NIT Trichy', 'NITT'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitk',
    name: 'National Institute of Technology Karnataka, Surathkal',
    country: 'India',
    city: 'Surathkal',
    state: 'Karnataka',
    abbreviations: ['NIT Surathkal', 'NITK'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitr',
    name: 'National Institute of Technology Rourkela',
    country: 'India',
    city: 'Rourkela',
    state: 'Odisha',
    abbreviations: ['NIT Rourkela', 'NITR'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitw',
    name: 'National Institute of Technology Warangal',
    country: 'India',
    city: 'Warangal',
    state: 'Telangana',
    abbreviations: ['NIT Warangal', 'NITW'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitc',
    name: 'National Institute of Technology Calicut',
    country: 'India',
    city: 'Kozhikode',
    state: 'Kerala',
    abbreviations: ['NIT Calicut', 'NITC'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-vnit',
    name: 'Visvesvaraya National Institute of Technology',
    country: 'India',
    city: 'Nagpur',
    state: 'Maharashtra',
    abbreviations: ['VNIT Nagpur', 'VNIT'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-mnit',
    name: 'Malaviya National Institute of Technology Jaipur',
    country: 'India',
    city: 'Jaipur',
    state: 'Rajasthan',
    abbreviations: ['MNIT Jaipur', 'MNIT'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-mnnit',
    name: 'Motilal Nehru National Institute of Technology Allahabad',
    country: 'India',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    abbreviations: ['MNNIT Allahabad', 'NIT Allahabad'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-svnit',
    name: 'Sardar Vallabhbhai National Institute of Technology',
    country: 'India',
    city: 'Surat',
    state: 'Gujarat',
    abbreviations: ['SVNIT Surat', 'SVNIT'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitdgp',
    name: 'National Institute of Technology Durgapur',
    country: 'India',
    city: 'Durgapur',
    state: 'West Bengal',
    abbreviations: ['NIT Durgapur', 'NITDGP'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nits',
    name: 'National Institute of Technology Silchar',
    country: 'India',
    city: 'Silchar',
    state: 'Assam',
    abbreviations: ['NIT Silchar', 'NITS'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitkkr',
    name: 'National Institute of Technology Kurukshetra',
    country: 'India',
    city: 'Kurukshetra',
    state: 'Haryana',
    abbreviations: ['NIT Kurukshetra', 'NIT KKR'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-manit',
    name: 'Maulana Azad National Institute of Technology',
    country: 'India',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    abbreviations: ['MANIT Bhopal', 'NIT Bhopal'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitp',
    name: 'National Institute of Technology Patna',
    country: 'India',
    city: 'Patna',
    state: 'Bihar',
    abbreviations: ['NIT Patna', 'NITP'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitj',
    name: 'Dr. B. R. Ambedkar National Institute of Technology Jalandhar',
    country: 'India',
    city: 'Jalandhar',
    state: 'Punjab',
    abbreviations: ['NIT Jalandhar', 'NITJ'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitjsr',
    name: 'National Institute of Technology Jamshedpur',
    country: 'India',
    city: 'Jamshedpur',
    state: 'Jharkhand',
    abbreviations: ['NIT Jamshedpur', 'NITJSR'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitrr',
    name: 'National Institute of Technology Raipur',
    country: 'India',
    city: 'Raipur',
    state: 'Chhattisgarh',
    abbreviations: ['NIT Raipur'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nitsgr',
    name: 'National Institute of Technology Srinagar',
    country: 'India',
    city: 'Srinagar',
    state: 'Jammu and Kashmir',
    abbreviations: ['NIT Srinagar'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nit-delhi',
    name: 'National Institute of Technology Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['NIT Delhi', 'NITD'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nit-goa',
    name: 'National Institute of Technology Goa',
    country: 'India',
    city: 'Cuncolim',
    state: 'Goa',
    abbreviations: ['NIT Goa'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiest',
    name: 'Indian Institute of Engineering Science and Technology, Shibpur',
    country: 'India',
    city: 'Howrah',
    state: 'West Bengal',
    abbreviations: ['IIEST Shibpur', 'BESU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 4. IIITs (INDIAN INSTITUTES OF INFORMATION TECHNOLOGY)
  // ==========================================
  {
    id: 'inst-in-iiith',
    name: 'International Institute of Information Technology, Hyderabad',
    country: 'India',
    city: 'Hyderabad',
    state: 'Telangana',
    abbreviations: ['IIIT Hyderabad', 'IIITH'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiitb',
    name: 'International Institute of Information Technology, Bangalore',
    country: 'India',
    city: 'Bengaluru',
    state: 'Karnataka',
    abbreviations: ['IIIT Bangalore', 'IIITB'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiitd',
    name: 'Indraprastha Institute of Information Technology Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['IIIT Delhi', 'IIITD'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiita',
    name: 'Indian Institute of Information Technology, Allahabad',
    country: 'India',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    abbreviations: ['IIIT Allahabad', 'IIITA'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiitg',
    name: 'Atal Bihari Vajpayee Indian Institute of Information Technology and Management',
    country: 'India',
    city: 'Gwalior',
    state: 'Madhya Pradesh',
    abbreviations: ['IIITM Gwalior', 'ABVIIITM'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiitl',
    name: 'Indian Institute of Information Technology, Lucknow',
    country: 'India',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    abbreviations: ['IIIT Lucknow', 'IIITL'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiitpune',
    name: 'Indian Institute of Information Technology, Pune',
    country: 'India',
    city: 'Pune',
    state: 'Maharashtra',
    abbreviations: ['IIIT Pune'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 5. TOP RESEARCH & SCIENCE INSTITUTES (IISC, IISERs)
  // ==========================================
  {
    id: 'inst-in-iisc',
    name: 'Indian Institute of Science Bangalore',
    country: 'India',
    city: 'Bengaluru',
    state: 'Karnataka',
    abbreviations: ['IISc', 'IISc Bangalore'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiser-pune',
    name: 'Indian Institute of Science Education and Research, Pune',
    country: 'India',
    city: 'Pune',
    state: 'Maharashtra',
    abbreviations: ['IISER Pune'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiser-kolkata',
    name: 'Indian Institute of Science Education and Research, Kolkata',
    country: 'India',
    city: 'Mohanpur',
    state: 'West Bengal',
    abbreviations: ['IISER Kolkata'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiser-mohali',
    name: 'Indian Institute of Science Education and Research, Mohali',
    country: 'India',
    city: 'Mohali',
    state: 'Punjab',
    abbreviations: ['IISER Mohali'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiser-bhopal',
    name: 'Indian Institute of Science Education and Research, Bhopal',
    country: 'India',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    abbreviations: ['IISER Bhopal'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-tifr',
    name: 'Tata Institute of Fundamental Research',
    country: 'India',
    city: 'Mumbai',
    state: 'Maharashtra',
    abbreviations: ['TIFR Mumbai'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-isi',
    name: 'Indian Statistical Institute',
    country: 'India',
    city: 'Kolkata',
    state: 'West Bengal',
    abbreviations: ['ISI Kolkata', 'ISI Delhi', 'ISI'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 6. TOP MEDICAL COLLEGES (AIIMS, JIPMER, CMC)
  // ==========================================
  {
    id: 'inst-in-aiims-delhi',
    name: 'All India Institute of Medical Sciences, New Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['AIIMS Delhi', 'AIIMS New Delhi', 'AIIMS'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-aiims-jodhpur',
    name: 'All India Institute of Medical Sciences, Jodhpur',
    country: 'India',
    city: 'Jodhpur',
    state: 'Rajasthan',
    abbreviations: ['AIIMS Jodhpur'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-aiims-patna',
    name: 'All India Institute of Medical Sciences, Patna',
    country: 'India',
    city: 'Patna',
    state: 'Bihar',
    abbreviations: ['AIIMS Patna'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-aiims-bhopal',
    name: 'All India Institute of Medical Sciences, Bhopal',
    country: 'India',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    abbreviations: ['AIIMS Bhopal'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-aiims-rishikesh',
    name: 'All India Institute of Medical Sciences, Rishikesh',
    country: 'India',
    city: 'Rishikesh',
    state: 'Uttarakhand',
    abbreviations: ['AIIMS Rishikesh'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-aiims-bbs',
    name: 'All India Institute of Medical Sciences, Bhubaneswar',
    country: 'India',
    city: 'Bhubaneswar',
    state: 'Odisha',
    abbreviations: ['AIIMS Bhubaneswar'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-pgimer',
    name: 'Post Graduate Institute of Medical Education and Research',
    country: 'India',
    city: 'Chandigarh',
    state: 'Chandigarh',
    abbreviations: ['PGIMER Chandigarh', 'PGI'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cmc-vellore',
    name: 'Christian Medical College, Vellore',
    country: 'India',
    city: 'Vellore',
    state: 'Tamil Nadu',
    abbreviations: ['CMC Vellore'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-jipmer',
    name: 'Jawaharlal Institute of Postgraduate Medical Education and Research',
    country: 'India',
    city: 'Puducherry',
    state: 'Puducherry',
    abbreviations: ['JIPMER'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-kgmu',
    name: "King George's Medical University",
    country: 'India',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    abbreviations: ['KGMU Lucknow'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-mamc',
    name: 'Maulana Azad Medical College',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['MAMC Delhi'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 7. TOP MANAGEMENT INSTITUTES (IIMs)
  // ==========================================
  {
    id: 'inst-in-iima',
    name: 'Indian Institute of Management Ahmedabad',
    country: 'India',
    city: 'Ahmedabad',
    state: 'Gujarat',
    abbreviations: ['IIM Ahmedabad', 'IIMA'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iimb',
    name: 'Indian Institute of Management Bangalore',
    country: 'India',
    city: 'Bengaluru',
    state: 'Karnataka',
    abbreviations: ['IIM Bangalore', 'IIMB'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iimc',
    name: 'Indian Institute of Management Calcutta',
    country: 'India',
    city: 'Kolkata',
    state: 'West Bengal',
    abbreviations: ['IIM Calcutta', 'IIMC'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iiml',
    name: 'Indian Institute of Management Lucknow',
    country: 'India',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    abbreviations: ['IIM Lucknow', 'IIML'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iimk',
    name: 'Indian Institute of Management Kozhikode',
    country: 'India',
    city: 'Kozhikode',
    state: 'Kerala',
    abbreviations: ['IIM Kozhikode', 'IIMK'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iimi',
    name: 'Indian Institute of Management Indore',
    country: 'India',
    city: 'Indore',
    state: 'Madhya Pradesh',
    abbreviations: ['IIM Indore', 'IIMI'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-iimm',
    name: 'Indian Institute of Management Mumbai',
    country: 'India',
    city: 'Mumbai',
    state: 'Maharashtra',
    abbreviations: ['IIM Mumbai', 'NITIE'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-xlri',
    name: 'XLRI – Xavier School of Management',
    country: 'India',
    city: 'Jamshedpur',
    state: 'Jharkhand',
    abbreviations: ['XLRI Jamshedpur', 'XLRI'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-fms-delhi',
    name: 'Faculty of Management Studies, University of Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['FMS Delhi', 'FMS'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 8. TOP NATIONAL LAW UNIVERSITIES (NLUs)
  // ==========================================
  {
    id: 'inst-in-nlsiu',
    name: 'National Law School of India University',
    country: 'India',
    city: 'Bengaluru',
    state: 'Karnataka',
    abbreviations: ['NLSIU', 'NLU Bangalore'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nalsar',
    name: 'NALSAR University of Law',
    country: 'India',
    city: 'Hyderabad',
    state: 'Telangana',
    abbreviations: ['NALSAR Hyderabad', 'NALSAR'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-wbnujs',
    name: 'The West Bengal National University of Juridical Sciences',
    country: 'India',
    city: 'Kolkata',
    state: 'West Bengal',
    abbreviations: ['WBNUJS', 'NUJS Kolkata'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nlud',
    name: 'National Law University Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['NLU Delhi', 'NLUD'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nluj',
    name: 'National Law University, Jodhpur',
    country: 'India',
    city: 'Jodhpur',
    state: 'Rajasthan',
    abbreviations: ['NLU Jodhpur', 'NLUJ'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-gnlu',
    name: 'Gujarat National Law University',
    country: 'India',
    city: 'Gandhinagar',
    state: 'Gujarat',
    abbreviations: ['GNLU Gandhinagar'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 9. PREMIER STATE UNIVERSITIES & TECH INSTITUTES
  // ==========================================
  {
    id: 'inst-in-jadavpur',
    name: 'Jadavpur University',
    country: 'India',
    city: 'Kolkata',
    state: 'West Bengal',
    abbreviations: ['JU Kolkata'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-calcutta-univ',
    name: 'University of Calcutta',
    country: 'India',
    city: 'Kolkata',
    state: 'West Bengal',
    abbreviations: ['Calcutta University', 'CU Kolkata'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-anna-univ',
    name: 'Anna University',
    country: 'India',
    city: 'Chennai',
    state: 'Tamil Nadu',
    abbreviations: ['Anna University Chennai'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-sppu',
    name: 'Savitribai Phule Pune University',
    country: 'India',
    city: 'Pune',
    state: 'Maharashtra',
    abbreviations: ['SPPU', 'Pune University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-mu',
    name: 'University of Mumbai',
    country: 'India',
    city: 'Mumbai',
    state: 'Maharashtra',
    abbreviations: ['Mumbai University', 'MU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-dtu',
    name: 'Delhi Technological University',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['DTU', 'DCE'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nsut',
    name: 'Netaji Subhas University of Technology',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['NSUT', 'NSIT'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-ggsipu',
    name: 'Guru Gobind Singh Indraprastha University',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['GGSIPU', 'IP University', 'IPU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-panjab-univ',
    name: 'Panjab University',
    country: 'India',
    city: 'Chandigarh',
    state: 'Chandigarh',
    abbreviations: ['PU Chandigarh', 'Panjab University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-osmania',
    name: 'Osmania University',
    country: 'India',
    city: 'Hyderabad',
    state: 'Telangana',
    abbreviations: ['OU Hyderabad', 'Osmania'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-andhra-univ',
    name: 'Andhra University',
    country: 'India',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    abbreviations: ['AU Vizag', 'Andhra University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-coep',
    name: 'COEP Technological University',
    country: 'India',
    city: 'Pune',
    state: 'Maharashtra',
    abbreviations: ['COEP Pune', 'COEP'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-vjti',
    name: 'Veermata Jijabai Technological Institute',
    country: 'India',
    city: 'Mumbai',
    state: 'Maharashtra',
    abbreviations: ['VJTI Mumbai', 'VJTI'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-ict-mumbai',
    name: 'Institute of Chemical Technology',
    country: 'India',
    city: 'Mumbai',
    state: 'Maharashtra',
    abbreviations: ['ICT Mumbai', 'UDCT'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-patna-univ',
    name: 'Patna University',
    country: 'India',
    city: 'Patna',
    state: 'Bihar',
    abbreviations: ['PU Patna'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-lucknow-univ',
    name: 'University of Lucknow',
    country: 'India',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    abbreviations: ['Lucknow University', 'LU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-rajasthan-univ',
    name: 'University of Rajasthan',
    country: 'India',
    city: 'Jaipur',
    state: 'Rajasthan',
    abbreviations: ['RU Jaipur', 'Rajasthan University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-gujarat-univ',
    name: 'Gujarat University',
    country: 'India',
    city: 'Ahmedabad',
    state: 'Gujarat',
    abbreviations: ['GU Ahmedabad'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-kerala-univ',
    name: 'University of Kerala',
    country: 'India',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    abbreviations: ['Kerala University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cusat',
    name: 'Cochin University of Science and Technology',
    country: 'India',
    city: 'Kochi',
    state: 'Kerala',
    abbreviations: ['CUSAT Kochi', 'CUSAT'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 10. PREMIER DEEMED & PRIVATE UNIVERSITIES
  // ==========================================
  {
    id: 'inst-in-bits-pilani',
    name: 'Birla Institute of Technology and Science, Pilani',
    country: 'India',
    city: 'Pilani',
    state: 'Rajasthan',
    abbreviations: ['BITS Pilani', 'BITS Goa', 'BITS Hyderabad', 'BITS'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-vit',
    name: 'Vellore Institute of Technology',
    country: 'India',
    city: 'Vellore',
    state: 'Tamil Nadu',
    abbreviations: ['VIT Vellore', 'VIT Chennai', 'VIT Bhopal', 'VIT-AP', 'VIT'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-mahe',
    name: 'Manipal Academy of Higher Education',
    country: 'India',
    city: 'Manipal',
    state: 'Karnataka',
    abbreviations: ['MAHE', 'Manipal University', 'MIT Manipal'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-thapar',
    name: 'Thapar Institute of Engineering and Technology',
    country: 'India',
    city: 'Patiala',
    state: 'Punjab',
    abbreviations: ['Thapar University', 'TIET Patiala'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-srm',
    name: 'SRM Institute of Science and Technology',
    country: 'India',
    city: 'Kattankulathur',
    state: 'Tamil Nadu',
    abbreviations: ['SRM University', 'SRM Chennai', 'SRM'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-amrita',
    name: 'Amrita Vishwa Vidyapeetham',
    country: 'India',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    abbreviations: ['Amrita University', 'Amrita'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-ashoka',
    name: 'Ashoka University',
    country: 'India',
    city: 'Sonipat',
    state: 'Haryana',
    abbreviations: ['Ashoka'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-jgu',
    name: 'O.P. Jindal Global University',
    country: 'India',
    city: 'Sonipat',
    state: 'Haryana',
    abbreviations: ['JGU Sonipat', 'Jindal Global University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-snu',
    name: 'Shiv Nadar University',
    country: 'India',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    abbreviations: ['SNU Noida'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-kiit',
    name: 'Kalinga Institute of Industrial Technology',
    country: 'India',
    city: 'Bhubaneswar',
    state: 'Odisha',
    abbreviations: ['KIIT University', 'KIIT'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-amity',
    name: 'Amity University',
    country: 'India',
    city: 'Noida',
    state: 'Uttar Pradesh',
    abbreviations: ['Amity Noida', 'Amity'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-lpu',
    name: 'Lovely Professional University',
    country: 'India',
    city: 'Phagwara',
    state: 'Punjab',
    abbreviations: ['LPU Punjab', 'LPU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-cu-punjab',
    name: 'Chandigarh University',
    country: 'India',
    city: 'Mohali',
    state: 'Punjab',
    abbreviations: ['CU Mohali', 'Chandigarh University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-symbiosis',
    name: 'Symbiosis International University',
    country: 'India',
    city: 'Pune',
    state: 'Maharashtra',
    abbreviations: ['SIU Pune', 'Symbiosis'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-nmims',
    name: 'Narsee Monjee Institute of Management Studies',
    country: 'India',
    city: 'Mumbai',
    state: 'Maharashtra',
    abbreviations: ['NMIMS Mumbai', 'NMIMS'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-christ',
    name: 'Christ University',
    country: 'India',
    city: 'Bengaluru',
    state: 'Karnataka',
    abbreviations: ['Christ University Bangalore'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-pes',
    name: 'PES University',
    country: 'India',
    city: 'Bengaluru',
    state: 'Karnataka',
    abbreviations: ['PESIT', 'PES Bangalore'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-rvce',
    name: 'RV College of Engineering',
    country: 'India',
    city: 'Bengaluru',
    state: 'Karnataka',
    abbreviations: ['RVCE', 'RV University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-bmsce',
    name: 'BMS College of Engineering',
    country: 'India',
    city: 'Bengaluru',
    state: 'Karnataka',
    abbreviations: ['BMSCE Bangalore'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-msrit',
    name: 'Ramaiah Institute of Technology',
    country: 'India',
    city: 'Bengaluru',
    state: 'Karnataka',
    abbreviations: ['MSRIT Bangalore', 'MS Ramaiah'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-psg',
    name: 'PSG College of Technology',
    country: 'India',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    abbreviations: ['PSG Tech', 'PSG'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-sastra',
    name: 'SASTRA Deemed to be University',
    country: 'India',
    city: 'Thanjavur',
    state: 'Tamil Nadu',
    abbreviations: ['SASTRA University'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-bit-mesra',
    name: 'Birla Institute of Technology, Mesra',
    country: 'India',
    city: 'Ranchi',
    state: 'Jharkhand',
    abbreviations: ['BIT Mesra'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 11. TOP PREMIER COLLEGES (DELHI UNIVERSITY & NATIONAL)
  // ==========================================
  {
    id: 'inst-in-miranda-house',
    name: 'Miranda House, University of Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['Miranda House', 'MH DU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-hindu-college',
    name: 'Hindu College, University of Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['Hindu College', 'Hindu DU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-stephens',
    name: "St. Stephen's College, University of Delhi",
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ["St. Stephen's", 'Stephens DU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-srcc',
    name: 'Shri Ram College of Commerce, University of Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['SRCC', 'SRCC DU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-lsr',
    name: 'Lady Shri Ram College for Women, University of Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['LSR', 'LSR DU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-hansraj',
    name: 'Hansraj College, University of Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['Hansraj College', 'Hansraj DU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-kmc',
    name: 'Kirori Mal College, University of Delhi',
    country: 'India',
    city: 'New Delhi',
    state: 'Delhi',
    abbreviations: ['KMC', 'Kirori Mal DU'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-loyola',
    name: 'Loyola College, Chennai',
    country: 'India',
    city: 'Chennai',
    state: 'Tamil Nadu',
    abbreviations: ['Loyola Chennai', 'Loyola'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-sxck',
    name: "St. Xavier's College, Kolkata",
    country: 'India',
    city: 'Kolkata',
    state: 'West Bengal',
    abbreviations: ["St. Xavier's Kolkata", 'SXCK'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'inst-in-sxcm',
    name: "St. Xavier's College, Mumbai",
    country: 'India',
    city: 'Mumbai',
    state: 'Maharashtra',
    abbreviations: ["St. Xavier's Mumbai", 'SXCM'],
    source: 'official_database',
    verified: true,
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
];
